module.exports = {
    "blocks": false,
    "brackets": "always",
    "colons": "always",
    "colors": "always",
    "commaSpace": "always",
    "commentSpace": "always",
    "cssLiteral": "never",
    "depthLimit": false,
    "duplicates": true,
    "efficient": "always",
    "exclude": [],
    "extendPref": "@extends",
    "globalDupe": true,
    "groupOutputByFile": true,
    "indentPref": false,
    "leadingZero": "always",
    "maxErrors": false,
    "maxWarnings": false,
    "mixed": false,
    "namingConvention": 'camelCase',
    "namingConventionStrict": false,
    "none": "always",
    "noImportant": true,
    "parenSpace": "never",
    "placeholders": "always",
    "prefixVarsWithDollar": "always",
    "quotePref": 'single',
    "semicolons": "always",
    "sortOrder": "false",
    "stackedProperties": "never",
    "trailingWhitespace": "never",
    "universal": false,
    "valid": true,
    "zeroUnits": "always",
    "zIndexNormalize": false,
    //"customProperties": [], -- no description
    //"mixins": [],  -- no description
    "reporterOptions": {
        "columns": ["lineData", "severity", "description", "rule"],
        "columnSplitter": "  ",
        "showHeaders": false,
        "truncate": true
    }
};
